export interface EnqueteDataRow {
  id: string;
  reference: string;
  operateur: string;
  nif: string;
  bureau: string;
  regime: string;
  marchandise: string;
  valeurUSD: number;
  statut: 'CRITIQUE' | 'EN_COURS' | 'EN_ATTENTE' | 'CONFORME' | 'CONTENTIEUX';
  priorite: 'URGENTE' | 'NORMALE' | 'SURVEILLANCE';
  echeance: string;
  joursRestants: number;
  inspecteur: string;
  tauxRisque: number;
  anomalieDetectee: string;
  piecesFournies: number;
  piecesTotal: number;
  derniereAction: string;
  tags: string[];
}

export const mockEnquetesData: EnqueteDataRow[] = [
  {
    id: 'row-001',
    reference: 'DGDA/DRK/DIR-ENQ/2026/0842',
    operateur: 'CONGO MINING & CHEMICAL LOGISTICS SAS',
    nif: 'A0812904X',
    bureau: 'Kasumbalesa (Bureau 401)',
    regime: 'IM4 — Importation directe',
    marchandise: 'Réactifs miniers & floculants de flottation',
    valeurUSD: 2555000,
    statut: 'CRITIQUE',
    priorite: 'URGENTE',
    echeance: '2026-10-15',
    joursRestants: 3,
    inspecteur: 'Insp. Marc Kabamba',
    tauxRisque: 92,
    anomalieDetectee: 'Minoration de fret maritime CIF de 34% constatée sur connaissements originaux',
    piecesFournies: 2,
    piecesTotal: 4,
    derniereAction: 'Relevés bancaires SWIFT MT103 réclamés à la TMB',
    tags: ['Minerais', 'Fret CIF', 'SYDONIA'],
  },
  {
    id: 'row-002',
    reference: 'DGDA/DRK/DIR-ENQ/2026/0843',
    operateur: 'KATANGA COBALT TRADING SPRL',
    nif: 'A1409211K',
    bureau: 'Kolwezi Commercial (Bureau 405)',
    regime: 'EX1 — Exportation définitive',
    marchandise: 'Hydroxyde de cobalt & concentrés cuivre',
    valeurUSD: 8420000,
    statut: 'CONTENTIEUX',
    priorite: 'URGENTE',
    echeance: '2026-10-18',
    joursRestants: 6,
    inspecteur: 'Insp. Adjoint Mireille Kabamba',
    tauxRisque: 88,
    anomalieDetectee: 'Écart de teneur métallique entre déclaration SYDONIA et bulletin OCC (diff. 4.2%)',
    piecesFournies: 3,
    piecesTotal: 3,
    derniereAction: 'Rapport d’infraction transmis à la direction contentieuse GELEC',
    tags: ['Cobalt', 'Contentieux', 'OCC'],
  },
  {
    id: 'row-003',
    reference: 'DGDA/DRK/DIR-ENQ/2026/0844',
    operateur: 'GRANDS LACS PETROLEUM SERVICES',
    nif: 'A0301988M',
    bureau: 'Kasumbalesa (Bureau 401)',
    regime: 'IT1 — Transit international',
    marchandise: 'Carburant Gasoil 50 ppm sous douane',
    valeurUSD: 1890000,
    statut: 'EN_ATTENTE',
    priorite: 'NORMALE',
    echeance: '2026-10-24',
    joursRestants: 12,
    inspecteur: 'Insp. Marc Kabamba',
    tauxRisque: 64,
    anomalieDetectee: 'Délai d’apurement du manifeste de transit dépassé au bureau de dépotage',
    piecesFournies: 1,
    piecesTotal: 3,
    derniereAction: 'Mise en demeure envoyée au commissionnaire en douane',
    tags: ['Hydrocarbures', 'Transit'],
  },
  {
    id: 'row-004',
    reference: 'DGDA/DRK/DIR-ENQ/2026/0845',
    operateur: 'SOCIÉTÉ AFRICAINE D’IMPORTATION ET COMMERCE (SAIC)',
    nif: 'A0789234R',
    bureau: 'Lubumbashi Aéroport (Bureau 403)',
    regime: 'IM4 — Importation directe',
    marchandise: 'Équipements télécoms & routeurs industriels',
    valeurUSD: 940000,
    statut: 'EN_COURS',
    priorite: 'NORMALE',
    echeance: '2026-11-02',
    joursRestants: 21,
    inspecteur: 'Contrôleur Éric Tshimanga',
    tauxRisque: 45,
    anomalieDetectee: 'Classement tarifaire contesté sur les modules optiques (Position SH 8517.62)',
    piecesFournies: 4,
    piecesTotal: 5,
    derniereAction: 'Audition contradictoire programmée avec le déclarant',
    tags: ['Télécom', 'Classement SH'],
  },
  {
    id: 'row-005',
    reference: 'DGDA/DRK/DIR-ENQ/2026/0846',
    operateur: 'LUALABA COPPER & AGGREGATES SARL',
    nif: 'A1904322T',
    bureau: 'Kolwezi Commercial (Bureau 405)',
    regime: 'IM7 — Entrepôt de douane',
    marchandise: 'Pneumatiques pour engins géants de mine',
    valeurUSD: 1320000,
    statut: 'CONFORME',
    priorite: 'SURVEILLANCE',
    echeance: '2026-11-15',
    joursRestants: 34,
    inspecteur: 'Insp. Marc Kabamba',
    tauxRisque: 18,
    anomalieDetectee: 'Aucune anomalie après vérification physique et contrôle des déclarations antérieures',
    piecesFournies: 6,
    piecesTotal: 6,
    derniereAction: 'PV de clôture conforme signé par le chef d’unité',
    tags: ['Matériel minier', 'Vérifié'],
  },
  {
    id: 'row-006',
    reference: 'DGDA/DRK/DIR-ENQ/2026/0847',
    operateur: 'TRANS-TANGANYIKA LOGISTICS SA',
    nif: 'A0543219P',
    bureau: 'Kalemie Port (Bureau 407)',
    regime: 'EX1 — Exportation',
    marchandise: 'Bois d’œuvre et grumes sciées',
    valeurUSD: 620000,
    statut: 'CRITIQUE',
    priorite: 'URGENTE',
    echeance: '2026-10-12',
    joursRestants: 1,
    inspecteur: 'Insp. Adjoint Mireille Kabamba',
    tauxRisque: 95,
    anomalieDetectee: 'Soupçon de fausse déclaration d’espèce (essence protégée CITES)',
    piecesFournies: 1,
    piecesTotal: 4,
    derniereAction: 'Blocage conservatoire requis auprès du chef de bureau de Kalemie',
    tags: ['CITES', 'Alerte Verte', 'Douane Portuaire'],
  },
  {
    id: 'row-007',
    reference: 'DGDA/DRK/DIR-ENQ/2026/0848',
    operateur: 'GÉCAMINES SA / SOUS-TRAITANTS',
    nif: 'A0001001A',
    bureau: 'Lubumbashi Gare (Bureau 402)',
    regime: 'IM4 — Importation directe',
    marchandise: 'Broyeurs à boulets et pièces de rechange',
    valeurUSD: 3450000,
    statut: 'EN_COURS',
    priorite: 'NORMALE',
    echeance: '2026-11-20',
    joursRestants: 39,
    inspecteur: 'Insp. Marc Kabamba',
    tauxRisque: 38,
    anomalieDetectee: 'Vérification de l’exonération au titre du Code Minier (Article 220)',
    piecesFournies: 5,
    piecesTotal: 7,
    derniereAction: 'Attestation ministérielle en cours d’authentification',
    tags: ['Code Minier', 'Exonérations'],
  },
  {
    id: 'row-008',
    reference: 'DGDA/DRK/DIR-ENQ/2026/0849',
    operateur: 'HAUT-KATANGA AGRO-INDUSTRIES',
    nif: 'A0987123V',
    bureau: 'Kasumbalesa (Bureau 401)',
    regime: 'IM4 — Importation directe',
    marchandise: 'Engrais azotés & fertilisants agricoles',
    valeurUSD: 780000,
    statut: 'CONFORME',
    priorite: 'SURVEILLANCE',
    echeance: '2026-11-28',
    joursRestants: 47,
    inspecteur: 'Contrôleur Éric Tshimanga',
    tauxRisque: 12,
    anomalieDetectee: 'Conformité totale des factures fournisseurs et acquittement régulier de la taxe DGI',
    piecesFournies: 5,
    piecesTotal: 5,
    derniereAction: 'Clôture sans suite contentieuse archivée',
    tags: ['Agro', 'Exonéré'],
  },
];
